name: CI
on:
  push:
  schedule:
    - cron: "0 0 * * *" # every day
jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: yarn
      - name: Lint Package
        run: yarn lint
      - name: Test Package
        env:
          HIDE_MY_NAME_VPN_CODE: ${{ secrets.HIDE_MY_NAME_VPN_CODE }}
        run: yarn test
      - name: Build Package
        run: yarn build
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.1.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

