name: Publish Package (GitHub)
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com/hi-imcodeman"
          # Defaults to the user or organization that owns the workflow file
          scope: "@hi-imcodeman"
      - run: npm install
      - run: npm run gpr-setup
      - run: npm run build
      # Publish to GitHub Packages
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.IMCODEMAN_PACKAGE_TOKEN }}
